//This file is automatically generated by generator.lua from https://github.com/Tenarion/cimguiextra
//based on distinct headers files made for imgui
#ifndef CIMGUIKNOBS_INCLUDED
#define CIMGUIKNOBS_INCLUDED

#include "cimgui.h"

#ifdef CIMGUI_DEFINE_ENUMS_AND_STRUCTS

typedef int ImGuiKnobFlags;
typedef enum {
    ImGuiKnobFlags_NoTitle = 1 << 0,
    ImGuiKnobFlags_NoInput = 1 << 1,
    ImGuiKnobFlags_ValueTooltip = 1 << 2,
    ImGuiKnobFlags_DragHorizontal = 1 << 3,
    ImGuiKnobFlags_DragVertical = 1 << 4,
    ImGuiKnobFlags_Logarithmic = 1 << 5,
    ImGuiKnobFlags_AlwaysClamp = 1 << 6
}ImGuiKnobFlags_;
typedef int ImGuiKnobVariant;
typedef enum {
    ImGuiKnobVariant_Tick = 1 << 0,
    ImGuiKnobVariant_Dot = 1 << 1,
    ImGuiKnobVariant_Wiper = 1 << 2,
    ImGuiKnobVariant_WiperOnly = 1 << 3,
    ImGuiKnobVariant_WiperDot = 1 << 4,
    ImGuiKnobVariant_Stepped = 1 << 5,
    ImGuiKnobVariant_Space = 1 << 6,
}ImGuiKnobVariant_;
typedef struct color_set color_set;
struct color_set
{
        ImColor base;
        ImColor hovered;
        ImColor active;
};
#else
#endif // CIMGUI_DEFINE_ENUMS_AND_STRUCTS

#ifndef CIMGUI_DEFINE_ENUMS_AND_STRUCTS
typedef ImGuiKnobs::color_set color_set;
#endif //CIMGUI_DEFINE_ENUMS_AND_STRUCTS
CIMGUI_API color_set* color_set_color_set_Color(ImColor base,ImColor hovered,ImColor active);
CIMGUI_API void color_set_destroy(color_set* self);
CIMGUI_API color_set* color_set_color_set_Nil(ImColor color);
CIMGUI_API bool ImGuiKnobs_Knob(const char* label,float* p_value,float v_min,float v_max,float speed,const char* format,ImGuiKnobVariant variant,float size,ImGuiKnobFlags flags,int steps,float angle_min,float angle_max);
CIMGUI_API bool ImGuiKnobs_KnobInt(const char* label,int* p_value,int v_min,int v_max,float speed,const char* format,ImGuiKnobVariant variant,float size,ImGuiKnobFlags flags,int steps,float angle_min,float angle_max);



#endif //CIMGUIKNOBS_INCLUDED
