//This file is automatically generated by generator.lua from https://github.com/Tenarion/cimguiextra
//based on distinct headers files made for imgui
#include "imgui.h"
#include "imgui_internal.h"
#include "./imgui-knobs/imgui_knobs.h"
#include "cimgui_knobs.h"



CIMGUI_API color_set* color_set_color_set_Color(ImColor base,ImColor hovered,ImColor active)
{
    return IM_NEW(color_set)(base,hovered,active);
}
CIMGUI_API void color_set_destroy(color_set* self)
{
    IM_DELETE(self);
}
CIMGUI_API color_set* color_set_color_set_Nil(ImColor color)
{
    return IM_NEW(color_set)(color);
}
CIMGUI_API bool ImGuiKnobs_Knob(const char* label,float* p_value,float v_min,float v_max,float speed,const char* format,ImGuiKnobVariant variant,float size,ImGuiKnobFlags flags,int steps,float angle_min,float angle_max)
{
    return ImGuiKnobs::Knob(label,p_value,v_min,v_max,speed,format,variant,size,flags,steps,angle_min,angle_max);
}
CIMGUI_API bool ImGuiKnobs_KnobInt(const char* label,int* p_value,int v_min,int v_max,float speed,const char* format,ImGuiKnobVariant variant,float size,ImGuiKnobFlags flags,int steps,float angle_min,float angle_max)
{
    return ImGuiKnobs::KnobInt(label,p_value,v_min,v_max,speed,format,variant,size,flags,steps,angle_min,angle_max);
}

